# Generated by Django 3.0.6 on 2020-05-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addanswer',
            name='ques_id',
            field=models.IntegerField(max_length=20),
        ),
    ]
