# Generated by Django 3.0.6 on 2020-05-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200527_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addanswer',
            name='ques_id',
            field=models.IntegerField(),
        ),
    ]
