# Generated by Django 3.0.6 on 2020-06-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200527_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='addanswer',
            name='img_ans',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='addanswer',
            name='ques_id',
            field=models.IntegerField(default=True),
        ),
    ]
